import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    static int counter = 0;

    public boolean isPrime(long num){
        double max = Math.sqrt(num) + 1;

        if (num == 2){
            counter++;
            return true;
        }
        if (num % 2 == 0){
            return false;
        }
        for (long i = 3; i<max ; i += 2){
            if (num % i == 0){
                return false;
            }
        }
        counter++;
        return true;
    }

    public String primeFactors(long number) {
        long n = number;
        String output = "";
        List<Integer> factors = new ArrayList<Integer>();
        for (int i = 2; i < number; i++) {
            boolean isPrimeNumber = true;

            // check to see if the number is prime
            for (int j = 2; j < i; j++) {
                if (i % j == 0) {
                    isPrimeNumber = false;
                    break; // exit the inner for loop
                }
            }

            // print the number if prime
            if (isPrimeNumber) {
                factors.add(i);
            }
        }

        for (int i =0; i<factors.size();i++){
            output = output + " "+factors.get(i);
        }
        return output;
    }

    public static void main(String[] args) {
//        App appObj2 = new App();
//        System.out.println(appObj2.primeFactors(29));
//        System.out.println(new App().getGreeting());

        if (args.length < 1 || args.length > 1){
            System.out.println("Please input a number as the program argument");
        }

        App appObj = new App();
        long input = Long.parseLong(args[0]);

        System.out.println(appObj.isPrime(input));
        System.out.println(appObj.isPrime(input*2+1));
        System.out.println(appObj.isPrime(37));
        System.out.println(appObj.primeFactors(input));
        System.out.println("There is "+counter+" prime numbers");
    }
}
